### ISSUE TITLE
New datasets

### ISSUE THREAD

**Issue by LinguList** [lexibank/lexibank-analysed#34]
Freshly coded:

* gravinachadic
* eppsnorthgermanic
* sidwellvietic 

Coded some time ago, but needs revision:

* grollemundbantu (orthography)
* tolmiebritishcolumbia (orthography)

**Comment by chrzyki** [comment]
I've done some very basic work on tolmiebritishcolumbia based on your issue (see this branch: https://github.com/lexibank/tolmiebritishcolumbia/tree/wip-profile) but would definitely need more help/guidance to continue with this and make it actually 'good'.

**Comment by FredericBlum** [comment]
@chrzyki What's the state on this? The issue in tolmiebritishcolumbia persists, but there was some PR related to ortho-profiles.

1. Is this already fixed, so we can close this issue?
2. If not, can @MuffinLinwist and I help you with the revision?

**Comment by chrzyki** [comment]
tolmiebritishcolumbia is done and just needs a new release. I'll do that today, thank you!

**Comment by chrzyki** [comment]
https://github.com/lexibank/tolmiebritishcolumbia/releases/tag/v1.0 was in fact already released with the updated profile and and CONTRIBUTORS, I just forgot to curate the issue accordingly, sorry!
