### ISSUE TITLE
Add figure to the Readme to Illustrate the differen *Core sets

### ISSUE THREAD

**Issue by LinguList** [lexibank/lexibank-analysed#36]
The figure is already finished and should be later added to the readme via notes.md when submitting version 1.0.

**Comment by FredericBlum** [comment]
Does this include the exact criteria for establishing the core sets? I have not found the exact numbers, but this would be quite useful for checking when adding new datasets

**Comment by FredericBlum** [comment]
@LinguList Do the criteria need to be updated for the upcoming release, or can you add the figure to the readme as it exists?

**Comment by LinguList** [comment]
Ups...

**Comment by LinguList** [comment]
[core-diagram.pdf](https://github.com/lexibank/lexibank-analysed/files/15337867/core-diagram.pdf)

This is my figure.

**Comment by LinguList** [comment]
![core-diagram](https://github.com/lexibank/lexibank-analysed/assets/2916210/51f704b9-2219-4f23-8dd5-b8800cad1dc7)
SVG is here.
