### ISSUE TITLE
Open problems in some datasets for the release of the Lexibank application

### ISSUE THREAD

**Issue by LinguList** [lexibank/lexibank-analysed#39]
Dataset | Note |
| --- | --- |
|idssegmented| segmented version of IDS, needs to be released or fed into IDS |
|tuled| We just take one release that works (need to check with concepts, etc.) |
|gravinachadic| needs to be checked by one more person |
|vanuatuvoices| needs to be released in a first version |
|sidwellvietic| needs concept list |
|wheelerutoaztecan | update dataset with new CLDF dataset ... title |
|chacolanguages| concept list needs to be added to concepticon |
|oskolskayatungusic| concept list can be taken from SawelyevTurkic |
|kochtukanoan| concept list not in concepticon
|lionnetyotonahua| conceptlist not in concepticon
|chaconnorthwestarawakan| conceptlist not in concepticon
|baf2| update with reference  from 2022 and DOI of paper concepts not in concepticon |
|tolmiebritishcolumbia | question to @chrzyki if we can or should add this |

**Comment by LinguList** [comment]
These issues should be addressed, so we can finalize all datasets. We do not need to include any of these datasets, but some would be nice, since they can also help for CLICS4.

**Comment by SimonGreenhill** [comment]
I'll take:

* wheelerutoaztecan
* oskolskayatungusic

**Comment by LinguList** [comment]
For oskolskaya, the conceptlist is just savekyev 2020 254 or similar.

**Comment by LinguList** [comment]
So this is even withiut 3.q releas of concepticon:)

**Comment by SimonGreenhill** [comment]
wheelerutoaztecan has been rebuilt: https://github.com/lexibank/wheelerutoaztecan/commit/a7e6f15c3b5c8259c97904bc68836550ccfc6435

**Comment by SimonGreenhill** [comment]
oskolskayatungusic is done.

**Comment by LinguList** [comment]
Nice, when did we add the list by Oskolskaya as such? This is what I like about concepticon recently: Lists get added without me noticing all details :) I left one minor issue there.

**Comment by LinguList** [comment]
@chrzyki, can you tell me on tolmiebritishcolumbia if you are fine to add it to Lexibank?

**Comment by chrzyki** [comment]
Sorry, missed the question in the table above! Sure - is there anything you'd like me to do/prepare for the data set?

**Comment by LinguList** [comment]
Is the concept list in concepticon? That would be a first question. And if you agree that we use it, as you have put lots of efforts into it and thought of an independent publication at some point.

**Comment by chrzyki** [comment]
> Is the concept list in concepticon? That would be a first question. And if you agree that we use it, as you have put lots of efforts into it and thought of an independent publication at some point.

Thanks! Yes, the concept list is in Concepticon:

https://concepticon.clld.org/contributions/Tolmie-1884-211

And absolutely, please feel free to use this in any context you see fit! I'd be happy to see the data getting used somewhere. I'd also be happy to check the data set again for any errors/mistakes (the language mapping is rather tricky for a number of the languages) or extend it further if need be.

**Comment by LinguList** [comment]
So the only task would be that you double-check, and help to release via Zenodo later, so we can add the DOI and include it in lexibank 1.0 via the web app :)

**Comment by LinguList** [comment]
Ah, we don't have orthoprofiles. That would be needed of course. If we cannot get them now, I'd not inlcude the data for now, but maybe help adding them later next year.

**Comment by chrzyki** [comment]
> So the only task would be that you double-check, and help to release via Zenodo later, so we can add the DOI and include it in lexibank 1.0 via the web app :)

I can help with that. :)

Orthoprofiles: Yes, no orthography profiles as of now, unfortunately. I can also help with that!

**Comment by LinguList** [comment]
Added an initial orthoprofile, @chrzyki, you can check and refine.

**Comment by chrzyki** [comment]
Thank you very much! I'll have a look and comment if necessary but for now this seems perfect.
