### ISSUE TITLE
Correct for Problematic Language Family Names in Data

### ISSUE THREAD

**Issue by LinguList** [lexibank/lexibank-analysed#46]
The language table reveals that we have some problematic language family names:

```

Abkhaz-Adyge
Abun
Afro-Asiatic
Ainu
Ainu (Japan)
Algic
Alsea
Andaqui
Angan
Anim
Araucanian
Arawakan
Arawan
Atakapa
Athabaskan-Eyak-Tlingit
Athapaskan-Eyak-Tlingit
Atlantic
Atlantic-Congo
Austro-Asiatic
Austroasiatic
Austronesian
Austronesian (Malayo-Polynesian: Central-Eastern Malayo-Polynesian: Eastern Malayo-Polynesian: South Halmahera-West New Guinea)
Aymara
Aymaran
Baining
Bangime
Barbacoan
Basque
Berta
Bilua
Bogaya
Bookkeeping
Boran
Border
Bororoan
Bosavi
Bunaban
Burushaski
Caddoan
Cahuapanan
Camsá
Candoshi-Shapra
Cariban
Cayubaba
Central Sudanic
Chapacuran
Chibcha
Chibchan
Chimakuan
Chinookan
Chocoan
Chonan
Chukotko-Kamchatkan
Chumashan
Cochimi-Yuman
Cofán
Coosan
Cuitlatec
Dagan
Daju
Dibiyaso
Dizoid
Dogon
Dravidian
Duna
East Bird's Head
East Strickland
Eastern Jebel
Eastern Trans-Fly
Eskimo-Aleut
Esselen
Fasu
Furan
Gagadu
Garrwan
Geelvink Bay
Goilalan
Great Andamanese
Guahibo
Guahiboan
Guaicuruan
Gumuz
Gunwinyguan
Hadza
Haida
Harakmbut
Hatam-Mansim
Heiban
Hmong-Mien
Hruso
Huarpean
Huavean
Huitotoan
Ijoid
Inanwatan
Indo-European
Iroquoian
Isolate
Itonama
Iwaidjan Proper
Japonic
Jarawa-Onge
Jarrakan
Jicaquean
Jivaroan
Jodi-Saliban
Kadugli-Krongo
Kakua-Nukak
Kamula
Kamula-Elevala
Kanoê
Karok
Kartvelian
Katla-Tima
Kaure-Kosare
Kawesqar
Kehu
Keram
Khoe-Kwadi
Kiowa-Tanoan
Kiwaian
Klamath-Modoc
Koiarian
Kol (Papua New Guinea)
Koman
Koreanic
Kru
Kuliak
Kunza
Kuot
Kusunda
Kwalean
Kwaza
Kxa
Lakes Plain
Lavukaleve
Left May
Lencan
Lengua-Mascoy
Limilngan
Lower Sepik-Ramu
Lule
Maban
Maiduan
Mailuan
Maipurean
Mairasi
Mande
Mangarrayi-Maran
Maningrida
Manubaran
Mao
Matacoan
Mayan
Maybrat
Maybrat-Karon
Mirndi
Misumalpam
Misumalpan
Miwok-Costanoan
Mixe-Zoque
Mongolic
Mosetén-Chimané
Movima
Muniche
Muskogean
N Caucasian
Nadahup
Naduhup
Nakh-Daghestanian
Nambiquaran
Nara
Natchez
Ndu
Nilotic
Nimboran
Nivkh
North Bougainville
North Halmahera
Nubian
Nuclear Eleman
Nuclear Torricelli
Nuclear Trans New Guinea
Nuclear-Macro-Je
Ongota
Otomanguean
Pahoturi
Palaihnihan
Pama-Nyungan
Panoan
Pauwasi
Pawaia
Peba-Yagua
Pele-Ata
Piawi
Pidgin
Pirahã
Pomoan
Puelche
Puinave
Pumé
Pyu
Páez
Quechuan
Sahaptian
Saharan
Saliban
Salinan
Salishan
Sandawe
Savosavo
Senagi
Sentani
Sepik
Seri
Shom Peng
Sino-Tibetan
Siouan
Sko
Songhay
South Bird's Head Family
South Bougainville
South Omotic
Southern Daly
Sulka
Sumerian
Surmic
Ta-Ne-Omotic
Tacanan
Tai-Kadai
Takelma
Tangkic
Tarascan
Taulil-Butam
Taushiro
Teberan
Tequistlatecan
Timor-Alor-Pantar
Timucua
Tiwi
Tor-Orya
Totonacan
Touo
Trumai
Tsimshian
Tucanoan
Tungusic
Tunica
Tupian
Turama-Kikori
Turkic
Tuu
Unattested
Uralic
Urarina
Uru-Chipaya
Uto-Aztecan
Wageman
Wakashan
Waorani
Warao
Washo
West Bomberai
Western Daly
Wintuan
Wiru
Worrorran
Yana
Yangmanic
Yanomam
Yareban
Yawa
Yele
Yeniseian
Yuat
Yukaghir
Yuki-Wappo
Yuracaré
Yuwana
Yámana
Zamucoan
Zaparoan
Zuni
```

**Comment by LinguList** [comment]
We have duplcates (Athab|paskan) and long names that are weird (Austronesian ...). These should be double-checked carefully.

**Comment by LinguList** [comment]
Note that "Family" in lexibank-cldf is a free field, it is not derived from Glottolog, or to put it in other words: it can be overwritten by CLDF conversion decisions.

**Comment by SimonGreenhill** [comment]
Do you know which languages these are attached to?

**Comment by LinguList** [comment]
We have this done in part. I do not know where these errors were introduced, but it is easy to check in the languages.csv. We need to trace the individual problems and correct them.

E.g., I just found the `Austronesian (Malayo-Polynesian: Central-Eastern Malayo-Polynesian: Eastern Malayo-Polynesian: South Halmahera-West New Guinea)` error in johanssonsoundsymbolic-Warembori. So this dataset needs to be scrutinized.

I think this is a perfect job for our student assistants and those who help to re-publish all datasets in CLDF via Zenodo, when Lexibank 1.0 is established and finalized.

**Comment by LinguList** [comment]
And it is as easy as checking [languages.csv](https://github.com/lexibank/lexibank-analysed/blob/main/cldf/languages.csv) online, noting down problematic datasets, filing and fixing issues, and done.

**Comment by FredericBlum** [comment]
@MuffinLinwist Did you also check the long language family names listed here, and the ones mentioned by Simon?  (https://github.com/lexibank/lexibank-analysed/issues/46#issuecomment-1489308897)

**Comment by FredericBlum** [comment]
@MuffinLinwist Tagging on this again

**Comment by MuffinLinwist** [comment]
Update: Now we are only waiting for [https://github.com/lexibank/transnewguineaorg/issues/24](https://github.com/lexibank/transnewguineaorg/issues/24) to close this issue. The fix needs to be from the upstream because the lexibank script is getting the data from `BASE_URL = "http://transnewguinea.org"`. I already tagged @SimonGreenhill on the issue in the repo.

**Comment by SimonGreenhill** [comment]
should be fixed now.

**Comment by FredericBlum** [comment]
Thanks!
