### ISSUE TITLE
Fill in Profile column in wordlist

### ISSUE THREAD

**Issue by xrotwang** [lexibank/lexibank-analysed#50]
To be able to retrieve the orthography profile used to segment a form, the Profile column should be filled in (and appropriate version info for the dataset).

**Comment by FredericBlum** [comment]
Is there a way to support you on this?

**Comment by LinguList** [comment]
Isn't hat already handled in the new lexibank version? We have the segmented version of each form in most profiles, we lack it only in those cases where we have segmented entries from the beginning (we could fill it in there "manually" by just pasting the segments).

**Comment by FredericBlum** [comment]
Then I will close this issue. If something else was meant, please re-open.
