### ISSUE TITLE
Workflow issues in getting data 

### ISSUE THREAD

**Issue by brochhagen** [lexibank/lexibank-analysed#53]
I've been following the [workflow](https://github.com/lexibank/lexibank-analysed/blob/v1.0/workflow.md) to get the data from LexiBank-analysed v1.0 but I've ran into some issues. I suppose some files/packages have changed since the document was written. 

### The issue

When I run
` cldfbench makecldf --with-cldfreadme lexibank_lexibank_analysed.py --glottolog ../glottolog`

I get an AttributeError:
```bash
INFO    running _cmd_makecldf on lexibank-analysed ...
Traceback (most recent call last):
  File "/opt/anaconda3/bin/cldfbench", line 33, in <module>
    sys.exit(load_entry_point('cldfbench==1.14.0', 'console_scripts', 'cldfbench')())
  File "/opt/anaconda3/lib/python3.9/site-packages/cldfbench-1.14.0-py3.9.egg/cldfbench/__main__.py", line 89, in main
    return args.main(args) or 0
  File "/opt/anaconda3/lib/python3.9/site-packages/cldfbench-1.14.0-py3.9.egg/cldfbench/commands/makecldf.py", line 32, in run
    with_dataset(args, 'makecldf')
  File "/opt/anaconda3/lib/python3.9/site-packages/cldfbench-1.14.0-py3.9.egg/cldfbench/cli_util.py", line 161, in with_dataset
    res = func(*arg, args)
  File "/opt/anaconda3/lib/python3.9/site-packages/pylexibank-3.4.0-py3.9.egg/pylexibank/dataset.py", line 218, in _cmd_makecldf
    super()._cmd_makecldf(args)
  File "/opt/anaconda3/lib/python3.9/site-packages/cldfbench-1.14.0-py3.9.egg/cldfbench/dataset.py", line 212, in _cmd_makecldf
    self.cmd_makecldf(args)
  File "/Users/tbroc/lexibank-analysed/./lexibank_lexibank_analysed.py", line 279, in cmd_makecldf
    self.concepticon.conceptsets.values()}
AttributeError: 'NoneType' object has no attribute 'conceptsets'
```

Since I'm not very familiar with the CLDF-pipeline and the package ecosystem (which makes  `lexibank_lexibank_analysed.py` line 279 not very transparent to me), I'm not sure whether this an issue I introduced. Help would be appreciated.

### Changes to the workflow I made
Step 1 from the [workflow](https://github.com/lexibank/lexibank-analysed/blob/v1.0/workflow.md) works seamlessly, as described. 

For Step 2 (downloading data collection), I have
```
cldfbench download lexibank_lexibank_analysed.py
```
instead of 
```
cldfbench download cldfbench_lexibank_analysed.py
```

I also had to install [cltoolkit](https://github.com/cldf/cltoolkit.git) manually for this to work. It apparently wasn't covered by the installations that were bundled in step 1.

For Step 3 (dataset creating), besides adjusting the name of the `.py`-file as above, when running 

```
 cldfbench makecldf --with-cldfreadme lexibank_lexibank_analysed.py
```

I got an error that `'Config /Users/tbroc/Library/Application Support/cldf/catalog.ini has no entry for glottolog'`. So I cloned a fresh version of glottolog and passed the path to it explicitly with the `--glottolog` flag:

```
cldfbench makecldf --with-cldfreadme lexibank_lexibank_analysed.py --glottolog ../../glottolog
```

And this is the step where I get the AttributeError I opened this issue with. 

If I get this to work, I can certainly do a pull request with an update to `workflow.md`. Thanks in advance for any guidance!

**Comment by xrotwang** [comment]
`lexibank.makecldf` has a `--concepticon` option which is used to set the attribute that isn't set in your case. See
```
$ cldfbench lexibank.makecldf -h
usage: cldfbench lexibank.makecldf [-h] [--entry-point ENTRY_POINT]
                                   [--glottolog GLOTTOLOG]
                                   [--glottolog-version GLOTTOLOG_VERSION]
                                   [--concepticon CONCEPTICON]
                                   [--concepticon-version CONCEPTICON_VERSION]
                                   [--clts CLTS] [--clts-version CLTS_VERSION]
                                   [--verbose] [--dev]
                                   DATASET

Run makecldf command of a dataset

positional arguments:
  DATASET               Dataset spec, either ID of installed dataset or path
                        to python module.

options:
  -h, --help            show this help message and exit
  --entry-point ENTRY_POINT
                        Name of entry_points to identify datasets (default:
                        lexibank.dataset)
  --glottolog GLOTTOLOG
                        Path to repository clone of Glottolog data (default:
                        None)
  --glottolog-version GLOTTOLOG_VERSION
                        Version of Glottolog data to checkout (default: None)
  --concepticon CONCEPTICON
                        Path to repository clone of Concepticon data (default:
                        None)
  --concepticon-version CONCEPTICON_VERSION
                        Version of Concepticon data to checkout (default:
                        None)
  --clts CLTS           Path to repository clone of Clts data (default: None)
  --clts-version CLTS_VERSION
                        Version of Clts data to checkout (default: None)
  --verbose
  --dev
```

**Comment by brochhagen** [comment]
Perfect. Thanks a lot. So, for the record, I was missing: cloning and explictly passing the paths to both concepticon and clts.

**Comment by LinguList** [comment]
Yes, and this is one example, where the published SQLITE may come in 
handy, since these resources will be integrated there directly...
