### ISSUE TITLE
Release & update datasets in preparation for Lexibank 2.0

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank-analysed#55]
As discussed in https://github.com/lexibank/ala/issues/36#issuecomment-1929032203 there are multiple datasets that either need a new release or an update due to changes (e.g. in Concepticon).

The [dataset list](https://github.com/lexibank/lexibank-analysed/blob/main/etc/lexibank.tsv) gives an overview concerning candidates for new/update releases and here we'll discuss in which order to proceed.

- [x] luangthongkumkaren: is released and has DOI (https://zenodo.org/records/10392172), updates needed?
- [x] oskolskayatungusic: more checks needed, is released and has DOI (https://zenodo.org/records/10404266)
- [x] othanieljen: is released and has a DOI (https://doi.org/10.5281/zenodo.10404212), update list
- [x] idssegmented: is released and has a DOI (https://zenodo.org/records/10404395), update list

**Comment by LinguList** [comment]
There are datasets that are not ready yet, so I'd need to check them as well another time. But as far as I can tell, lamanisoic should be fine.

**Comment by LinguList** [comment]
idssegmented has already a DOI, I think.

**Comment by FredericBlum** [comment]
This file differs a lot from the google spreadsheet that you have shared with me last year. I am now confused where we should actually update information about new databases?

**Comment by chrzyki** [comment]
I've updated the top issue with the datasets that have been mentioned. All of them have had a release but I can help checking them again if needed.

Another question that came to mind: We're getting closer to Concepticon 3.2.0 so it might be worthwhile to wait for the release until further updates? Theoretically, the updates from Concepticon 3.1.0 to 3.2.0 shouldn't affect too many datasets but it might be easier to wait for the release rather than to only release the datasets that aren't affected.

**Comment by LinguList** [comment]
@chrzyki yes, in fact, we should wait for Concepticon 3.2, but we should also hurry to include missing concept lists, I'll try to find time to check that later on.

@FredericBlum, with Lexibank 1.0, we modified the list to this form, did I share the list before 1.0 was published? In any case, the base format is the one you find there now ;-)

**Comment by SimonGreenhill** [comment]
Great -- are we adding new datasets too?

**Comment by chrzyki** [comment]
> Great -- are we adding new datasets too?

Yes. :)

I've updated the [`update-datasets`](https://github.com/lexibank/lexibank-analysed/tree/update-datasets) branch [with more datasets](https://github.com/lexibank/lexibank-analysed/commits/update-datasets/) from the Google Sheet, added additional DOIs and comments about datasets that now have their respective concept list in Concepticon.

**Comment by LinguList** [comment]
For lexibank 2.0 I want to exclude all datasets that don't have orthoprofiles. This means, clics1, and some others, also data not finished, should all be excluded. I'll later go through the list and delete them already.

**Comment by chrzyki** [comment]
Yes, If that's okay for you just mention those here and I'll remove them.

On Feb 8, 2024 10:43, Johann-Mattis List ***@***.***> wrote:

Or can I mention them here?

**Comment by FredericBlum** [comment]
If I understand the list correctly, it's only vanuatuvoices which has no concept list in Concepticon. But the list is already mapped, so this could be a quick addition. All other conceptlist have been added, but in most of those cases the lexibank-script still has to be adapted. We could just add this to our checklist when re-releasing all datasets.

**Comment by chrzyki** [comment]
Re vanuatuvoices: I'd have to investigate that further, maybe the list is already in there under a different name? I wasn't sure.

Re rebuilding: Yep, I'll start with slowly rebuilding and checking some of the datasets.

**Comment by LinguList** [comment]
I'd discard vanuatuvoices now, since the data is too sparse for anything, it has less than 80 concepts per language, and we have somethreshold of > 100 now there.

**Comment by LinguList** [comment]
`ids` must be discarded, superseded by `idssegmented`. There are a couple of lists that are not finished and should also not be used.

**Comment by xrotwang** [comment]
Yes, vanuatuvoices must be excluded. Despite that being discussed for years
there's still no proper release of the data currently on the website.
That's none of our business.

Johann-Mattis List ***@***.***> schrieb am Do., 8. Feb. 2024,
13:35:

**Comment by chrzyki** [comment]
More updates to concept lists & etc., tracked here: https://github.com/lexibank/lexibank-analysed/commits/update-datasets/etc/lexibank.tsv
