### ISSUE TITLE
Consonant clusters

### ISSUE THREAD

**Issue by FredericBlum** [lexibank/lexibank-analysed#57]
We now have the code to output the consonant clusters, but we need to check the individual datasets to see what we can improve. Potentially, we do this within the release pipeline as one of the checks. @chrzyki What do you think, should we add this to the workflow?

**Comment by chrzyki** [comment]
Yep, I'd definitely add it. The length of what constitutes a 'potentially problematic consonant cluster' might differ but this can be handled on per-dataset-basis I think.
