### ISSUE TITLE
Add Editors to datasets

### ISSUE THREAD

**Issue by FredericBlum** [lexibank/lexibank-analysed#58]
As discussed, we want to add the role of Editors to the Contributions.md.

@LinguList I think you self-assigned this task to you, right? Or should we make proposals for each dataset and only ask you in case of doubts, because of time-constraints on your side?

**Comment by LinguList** [comment]
I am fine with this variant, of being asked in doubt. My suggestion is 
specifically that you ask me in those cases where editors are people 
that have working for us for a longer time.

**Comment by FredericBlum** [comment]
@chrzyki @MuffinLinwist So we add the Editors based on who has worked 'a lot' on the dataset, and if in doubt, we ask in the Mattermost channel - would you agree with this?

**Comment by chrzyki** [comment]
Yep. Ask:

- when in doubt about inclusions
- if people are listed that haven't been working on the data (as `Other`) for a long time
