### ISSUE TITLE
Macro area: Eastern Nigeria, Northeast Africa

### ISSUE THREAD

**Issue by FredericBlum** [lexibank/lexibank-analysed#64]
The following datasets overwrite the Macroarea from Glottolog as 'Eastern Nigeria':

- kleinewillinghoeferbikwinjen
- otahnieljen

The following dataset overwrites as Northeast Africa:

- bremerberta

The following dataset overwrites as Southeast Asia:

- duonglachi

Given that we have not released the LB2.0 yet, I propose we change it directly in the individual datasets and make a new minor release for each. If you agree @LinguList @chrzyki I will take care of this.

**Comment by chrzyki** [comment]
Yes, I agree. Thanks for taking care of that.
