### ISSUE TITLE
Consonant clusters

### ISSUE THREAD

**Issue by FredericBlum** [lexibank/lexibank-analysed#65]
At least the following datasets still have major problems with consonant clusters:

- [ ] idssegmented
- [ ] kraftcahdic
- [ ] huntergatherer

**Comment by LinguList** [comment]
Okay, I would try to see if I can help with KraftChadic and HunterGatherer?

**Comment by FredericBlum** [comment]
All three PR's have now been created and the problems fixed. Once you have given your green light for merging, I will close this issue.

**Comment by LinguList** [comment]
Very nice, yes, many thanks :-) Green light from me.
